version: "3.8"

#see https://forums.docker.com/t/data-directory-var-lib-postgresql-data-pgdata-has-wrong-ownership/17963/26
services:
  sidb:
    container_name: siddata_server_db_1
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=siddata
      - POSTGRES_USER=siddata
      - POSTGRES_PASSWORD=siddata
  web:
    container_name: siddata_server_web_1
    build:
      context: .
      args:
        - uid=${COMPOSE_UID:-1000}
        - gid=${COMPOSE_GID:-1000}
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/opt/siddata_backend/:Z
    ports:
      - "8000:8000"
    depends_on:
      - sidb
    environment:
     - SIDDATA_ALLOWED_HOSTS=$SIDDATA_ALLOWED_HOSTS
     - SIDDATA_DEBUG=$SIDDATA_DEBUG
     - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE:-siddata_server.settings.development}
